### ISSUE TITLE
CORS request blocked for ipv6.nex.li

### ISSUE THREAD

**Issue by HerrMotz** [hell-sh/NexIP#1]
When accessing https://ip.nex.li/ I get this error printed in the console:
`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://ipv6.nex.li/ip. (Grund: CORS-Anschlag schlug fehl).`
The website prints the following:
`Your IPv6: Not available`
Also when you leave the website open, the amount of requests potentially increases, which causes your browser to lag after a while.
![grafik](https://user-images.githubusercontent.com/20333692/43995211-587f7d46-9daa-11e8-8a29-d0fbdb12030e.png)
User-Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0`

**Comment by timmyrs** [comment]
Could you please run `ping ipv6.nex.li -6` to make sure you even have an IPv6 address?

**Comment by HerrMotz** [comment]
![grafik](https://user-images.githubusercontent.com/20333692/43995949-2dea1776-9db9-11e8-8ad1-93ebc621ee0a.png)
![grafik](https://user-images.githubusercontent.com/20333692/43995952-49642bc2-9db9-11e8-88eb-e100e033c9dc.png)

**Comment by timmyrs** [comment]
Duh, I forgot to tell the server to listen on ::666 and not only on ::1

... I can't even joke right :(
